title: Jatin Sharma | Portfolio
email: jatinsaroch11@gmail.com
description: MS Research Student at IIT Indore | Machine Learning Enthusiast
baseurl: ""
url: "https://jatin-sharma-11.github.io"
github_username: Jatin-Sharma-11
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown