title: Jatin Sharma | Portfolio
email: jatinsaroch11@gmail.com
description: MS Research Student at IIT Indore | Machine Learning & Software Developer
baseurl: ""
url: "https://jatinsharma.github.io"
github_username: Jatin-Sharma-11
theme: minima # Base theme, we'll override with custom CSS
plugins:
  - jekyll-feed
  - jekyll-seo-tag